# Generated by Django 4.2.4 on 2023-08-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_subjects_subjectsmarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_name']},
        ),
    ]
