# Generated by Django 4.2.4 on 2023-08-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
