# Generated by Django 4.2.4 on 2023-08-08 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectsmarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentmark', to='students.student'),
        ),
    ]
