# Generated by Django 4.2.4 on 2023-08-11 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_reportcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportcard', to='students.student'),
        ),
    ]
